package MVoter;


import java.awt.Color;
import java.sql.*;
import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/*
 * To change this template, choose Tools | Templates
 * and open the tem

            @Override
            public StringBuffer format(Object obj, StringBuffer toAppendTo, FieldPosition pos) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Object parseObject(String source, ParsePosition pos) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }late in the editor.
 */

/*
 * after_login_interface.java
 *
 * 
 */

/**
 *
 * 
 */
public class after_login_interface extends javax.swing.JFrame {
    private JFrame f;
    Connection conn= null;
    String url = "jdbc:mysql://localhost/";
    String dbName = "db66001";
    String driver ="com.mysql.jdbc.Driver";
    String user = "root";
    String password = "";

    /*Connection conn = null;
    String url = "jdbc:mysql://192.168.170.15/";
    String dbName = "db66001";
    String driver = "com.mysql.jdbc.Driver";
    String userName = "66001";
    String password = "66001";*/
    Statement st;
    ResultSet rs;

    /** Creates new form after_login_interface */
    public after_login_interface() {

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);              
        
        
        try{
	       Class.forName(driver);

             conn = DriverManager.getConnection(url+dbName,user,password);

              st = conn.createStatement();

             this.setTitle("Voters Registration and Verification");

	            }


	            catch(Exception exp){
	              JOptionPane.showMessageDialog(null, "Cannot connect to the database,check network settings.","ERROR",JOptionPane.ERROR_MESSAGE);
	            }
        try {
            
            
            
	            rs = st.executeQuery("SELECT name FROM ward_database");
	            while(rs.next()){
                     ward_combo.addItem(rs.getString("name"));
                     ward_combo_election.addItem(rs.getString("name"));
                     ward_combo_verification.addItem(rs.getString("name"));
                    }
	            rs.close();
	            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),"ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
       
   
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        electionpane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_card_no = new javax.swing.JTextField();
        sur_name = new javax.swing.JTextField();
        Middle_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        malebutton = new javax.swing.JRadioButton();
        femalebutton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        voterid = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        datefield = new javax.swing.JFormattedTextField();
        polling_stations_combo = new javax.swing.JComboBox();
        place_of_issue_combo = new javax.swing.JComboBox();
        ward_combo = new javax.swing.JComboBox();
        constituency_textfield = new javax.swing.JTextField();
        county_textfield = new javax.swing.JTextField();
        date = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        verification_id_number = new javax.swing.JTextField();
        verification_voter_id = new javax.swing.JTextField();
        verification_button = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        verification_table = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        sn = new javax.swing.JTextField();
        mn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        v = new javax.swing.JTextField();
        place_of_issue_combo_verify = new javax.swing.JComboBox();
        ward_combo_verification = new javax.swing.JComboBox();
        v_con = new javax.swing.JTextField();
        v_cou = new javax.swing.JTextField();
        back_verification = new javax.swing.JButton();
        polling_stations_combo_ver = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        election_id = new javax.swing.JTextField();
        Election_date = new javax.swing.JTextField();
        add_new_election1 = new javax.swing.JButton();
        clear_button1 = new javax.swing.JButton();
        type_of_election_combobox = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();
        constituencycombobox_election = new javax.swing.JComboBox();
        countycombobox_election = new javax.swing.JComboBox();
        county_election1 = new javax.swing.JLabel();
        cons_election1 = new javax.swing.JLabel();
        ward_election1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        election_data_table = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        ward_combo_election = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        electionpane.setToolTipText("register a voter");
        electionpane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electionpane.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("ID Card Number");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel2.setText("VOTER  DETAILS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("SurName");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Middle Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("First Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Date of birth");

        id_card_no.setDocument(new TextfieldFilter(TextfieldFilter.NUMERIC));

        sur_name.setDocument(new TextfieldFilter(TextfieldFilter.letters));

        Middle_name.setDocument(new TextfieldFilter(TextfieldFilter.letters));

        last_name.setDocument(new TextfieldFilter(TextfieldFilter.letters));

        buttonGroup1.add(malebutton);
        malebutton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        malebutton.setText("Male");

        buttonGroup1.add(femalebutton);
        femalebutton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        femalebutton.setText("Female");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel8.setText("VOTER'S CARD DETAILS");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Voter ID");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Place of Issue");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Ward");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Constituency");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("County");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Polling Centre");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Date of Issue");

        voterid.setDocument(new TextfieldFilter(TextfieldFilter.NUMERIC));
        voterid.setEditable(false);

        savebutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        clearbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVoter/clear_left.png"))); // NOI18N
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVoter/log_out.png"))); // NOI18N
        jButton1.setText("Log_out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        datefield.setEditable(false);

        polling_stations_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gatwekera", "Kambi Muru", "Kangemi", "Kianda", "Kichinjio", "Kisumu Ndogo", "Laini Saba", "Lindi", "Makina", "Makongeni", "Mashimoni", "Mugumoini", "Kwetu", "Sarang'ombe", "Shilanga", "Siranga", "Soweto East", "Soweto West" }));

        place_of_issue_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Corner Mbaya", "Village", "Redeemed", "Mabatini", "Mathare ", "Mashimoni", "Kyamutisya", "Gitathuru", "Mlango Kubwa", "Mahira", "Madoya", "Kosovo", "Kambi Moto", "Kahonoki", "Grogon", "Huruma", "Gitathuru", "Ghetto", "Bondeni" }));
        place_of_issue_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_of_issue_comboActionPerformed(evt);
            }
        });

        ward_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Ward" }));
        ward_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ward_comboActionPerformed(evt);
            }
        });

        constituency_textfield.setEditable(false);

        county_textfield.setEditable(false);

        date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2030", "2029", "2028", "2027", "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901 " }));

        jLabel20.setText("ddd");

        jLabel21.setText("MMM");

        jLabel22.setText("YYYY");

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(76, 76, 76)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(id_card_no, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                .addComponent(sur_name, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                .addComponent(Middle_name, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                .addComponent(last_name, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(malebutton)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(femalebutton))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel20))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(month, 0, 64, Short.MAX_VALUE)
                                                        .addComponent(jLabel21))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel22)
                                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGap(194, 194, 194))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel11))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(county_textfield)
                                    .addComponent(constituency_textfield)
                                    .addComponent(ward_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(place_of_issue_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(polling_stations_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(datefield)
                                    .addComponent(voterid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addComponent(clearbutton))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(348, 348, 348))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addContainerGap(778, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id_card_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(voterid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sur_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(place_of_issue_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ward_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(constituency_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(malebutton)
                        .addComponent(femalebutton)
                        .addComponent(jLabel13))
                    .addComponent(county_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(polling_stations_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        malebutton.setActionCommand("Male");
        femalebutton.setActionCommand("Female");
        for(int i=0; i < 1 ; i++){
            voterid.setText(""+(int)(Math.random()*200));
        }
        Format formatter;
        formatter=new SimpleDateFormat("yyyy/MM/dd");
        java.util.Date utilDate = new java.util.Date();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        String today=formatter.format(sqlDate);
        datefield.setValue(today);

        electionpane.addTab("REGISTRATION", jPanel1);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("VOTER VERIFICATION");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("ID Card Number");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Voter ID");

        verification_voter_id.setDocument(new TextfieldFilter(TextfieldFilter.NUMERIC));

        verification_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        verification_button.setText("Verify");
        verification_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verification_buttonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        verification_table.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        verification_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, null, null, null, null, null, null, null, null, null},
                {"", "", null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        verification_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verification_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(verification_table);
        if (verification_table.getColumnModel().getColumnCount() > 0) {
            verification_table.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("VOTER DETAILS");

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        close_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        close_button.setText("Logout");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        jLabel23.setText("ID Number");

        jLabel24.setText("Sur Name");

        jLabel25.setText("Middle Name");

        jLabel26.setText("Last Name");

        jLabel27.setText("Gender");

        jLabel28.setText("Date Of Birth");

        jLabel33.setText("Voter ID");

        jLabel34.setText("Placeof Issue");

        jLabel35.setText("Ward");

        jLabel36.setText("Constituency");

        jLabel37.setText("County");

        jLabel38.setText("Polling Station");

        id.setEditable(false);

        sn.setEditable(false);
        sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snActionPerformed(evt);
            }
        });

        mn.setEditable(false);
        mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnActionPerformed(evt);
            }
        });

        ln.setEditable(false);
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });

        g.setEditable(false);
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        d.setEditable(false);

        v.setEditable(false);
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        place_of_issue_combo_verify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Corner Mbaya", "Village", "Redeemed", "Mabatini", "Mathare ", "Mashimoni", "Kyamutisya", "Gitathuru", "Mlango Kubwa", "Mahira", "Madoya", "Kosovo", "Kambi Moto", "Kahonoki", "Grogon", "Huruma", "Gitathuru", "Ghetto", "Bondeni" }));

        ward_combo_verification.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Ward" }));
        ward_combo_verification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ward_combo_verificationActionPerformed(evt);
            }
        });

        v_con.setEditable(false);

        v_cou.setEditable(false);

        back_verification.setText("Back");
        back_verification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_verificationActionPerformed(evt);
            }
        });

        polling_stations_combo_ver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gatwekera", "Kambi Muru", "Kangemi", "Kianda", "Kichinjio", "Kisumu Ndogo", "Laini Saba", "Lindi", "Makina", "Makongeni", "Mashimoni", "Mugumoini", "Kwetu", "Sarang'ombe", "Shilanga", "Siranga", "Soweto East", "Soweto West" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(verification_button, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(verification_voter_id, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(verification_id_number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton3))))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mn)
                                    .addComponent(sn)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(ln)
                                    .addComponent(g)
                                    .addComponent(d)))
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(polling_stations_combo_ver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(v_cou)
                            .addComponent(v_con)
                            .addComponent(ward_combo_verification, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(v)
                            .addComponent(place_of_issue_combo_verify, 0, 108, Short.MAX_VALUE))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(back_verification)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 681, Short.MAX_VALUE)
                        .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(verification_id_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(verification_voter_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verification_button)
                            .addComponent(jButton3))
                        .addGap(108, 108, 108)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34)
                                    .addComponent(place_of_issue_combo_verify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(mn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35)
                                    .addComponent(ward_combo_verification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26)
                                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36)
                                .addComponent(v_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(v_cou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(polling_stations_combo_ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_verification)
                    .addComponent(close_button))
                .addContainerGap())
        );

        electionpane.addTab("VERIFICATION", jPanel2);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel39.setText("ELECTION DETAILS");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel40.setText("Election ID");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel41.setText("Type");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel42.setText("Election Date");

        election_id.setEditable(false);
        election_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                election_idActionPerformed(evt);
            }
        });

        Election_date.setEditable(false);
        Election_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Election_dateActionPerformed(evt);
            }
        });

        add_new_election1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        add_new_election1.setText("save");
        add_new_election1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_election1ActionPerformed(evt);
            }
        });

        clear_button1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        clear_button1.setText("clear");
        clear_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_button1ActionPerformed(evt);
            }
        });

        type_of_election_combobox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        type_of_election_combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "General_Election", "County_By_Election", "Constituency_By_Election", "Ward_By_Election" }));
        type_of_election_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_of_election_comboboxActionPerformed(evt);
            }
        });

        jButton9.setText("set date");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        constituencycombobox_election.setFont(new java.awt.Font("Times New Roman", 0, 12));
        constituencycombobox_election.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"N/A","Dagoretti Constituency", "Embakasi Constituency", "Kamukunji Constituency", "Kasarani Constituency", "Langata Constituency", "Makadara Constituency", "Starehe Constituency", "Westlands Constituency", "Kinangop Constituency", "Kipipiri Constituency", "Ndaragwa Constituency", "Ol Kalou Constituency", "Kieni Constituency", "Mathira Constituency", "Mukurweini Constituency", "Nyeri Town Constituency", "Othaya Constituency", "Tetu Constituency", "Gichugu Constituency", "Ndia Constituency", "Mwea Constituency", "Kandara Constituency", "Kigumo Constituency", "Maragua Constituency", "Kangema Constituency", "Kiharu Constituency", "Mathioya Constituency", "Gatanga Constituency", "Gatundu South Constituency", "Gatundu North Constituency", "Juja Constituency", "Githunguri Constituency", "Kiambaa Constituency", "Kikuyu Constituency", "Limuru Constituency", "Lari Constituency", "Bahari Constituency", "Ganze Constituency", "Kaloleni Constituency", "Matuga Constituency", "Msambweni Constituency", "Lamu East Constituency", "Lamu West Constituency", "Magarini Constituency", "Malindi Constituency", "Changamwe Constituency", "Kisauni Constituency", "Likoni Constituency", "Mvita Constituency", "Mwatate Constituency", "Taveta Constituency", "Voi Constituency", "Wundanyi Constituency", "Bura Constituency", "Galole Constituency", "Garsen Constituency", "Manyatta Constituency", "Runyenjes Constituency", "Isiolo North Constituency", "Isiolo South Constituency", "Kitui Central Constituency", "Kitui South Constituency", "Kitui West Constituency", "Mutito Constituency", "Kangundo Constituency", "Kathiani Constituency", "Machakos Town Constituency", "Masinga Constituency", "Mwala Constituency", "Yatta Constituency", "Kaiti Constituency", "Kibwezi Constituency", "Kilome Constituency", "Makueni Constituency", "Mbooni Constituency", "Laisamis Constituency", "North Horr Constituency", "Saku Constituency", "Gachoka Constituency", "Siakago Constituency", "Central Imenti Constituency", "North Imenti Constituency", "South Imenti Constituency", "Igembe Constituency", "Ntonyiri Constituency", "Tigania East Constituency", "Tigania West Constituency", "Nithi Constituency", "Moyale Constituency", "Mwingi North Constituency", "Mwingi South Constituency", "Tharaka Constituency", "Dujis Constituency", "Fafi Constituency", "Lagdera Constituency", "Ijara Constituency", "Wajir East Constituency", "Wajir North Constituency", "Wajir South Constituency", "Wajir West Constituency", "Mandera Central Constituency", "Mandera East Constituency", "Mandera West Constituency", "Bondo Constituency", "Rarieda Constituency", "Bobasi Constituency", "Bomachoge Constituency", "South Mugirango Constituency", "Ndhiwa Constituency", "Rangwe Constituency", "Bonchari Constituency", "Kitutu Chache Constituency", "Nyaribari Chache Constituency", "Nyaribari Masaba Constituency", "Kisumu Rural Constituency", "Kisumu Town East Constituency", "Kisumu Town West Constituency", "Kuria Constituency", "Migori Constituency", "Nyatike Constituency", "Rongo Constituency", "Uriri Constituency", "Kitutu Masaba Constituency", "North Mugirango Constituency", "West Mugirango Constituency", "Muhoroni Constituency", "Nyakach Constituency", "Nyando Constituency", "Karachuonyo Constituency", "Kasipul Kabondo Constituency", "Alego Constituency", "Gem Constituency", "Ugenya Constituency", "Gwassi Constituency", "Mbita Constituency", "Baringo Central Constituency", "Baringo East Constituency", "Baringo North Constituency", "Bomet Constituency", "Chepalungu Constituency", "Sotik Constituency", "Bureti Constituency", "Konoin Constituency", "Kajiado Central Constituency", "Kajiado North Constituency", "Kajiado South Constituency", "Keiyo North Constituency", "Keiyo South Constituency", "Ainamoi Constituency", "Belgut Constituency", "Kipkelion Constituency", "Eldama Ravine Constituency", "Mogotio Constituency", "Laikipia East Constituency", "Laikipia West Constituency", "Marakwet East Constituency", "Marakwet West Constituency", "Molo Constituency", "Naivasha Constituency", "Nakuru Town Constituency", "Rongai Constituency", "Subukia Constituency", "Aldai Constituency", "Emgwen Constituency", "Mosop Constituency", "Tinderet Constituency", "Narok North Constituency", "Narok South Constituency", "Samburu East Constituency", "Samburu West Constituency", "Kilgoris Constituency", "Cherangany Constituency", "Kwanza Constituency", "Saboti Constituency", "Turkana Central Constituency", "Turkana North Constituency", "Turkana South Constituency", "Eldoret East Constituency", "Eldoret North Constituency", "Eldoret South Constituency", "Kacheliba Constituency", "Kapenguria Constituency", "Sigor Constituency", "Bumula Constituency", "Kanduyi Constituency", "Kimilili Constituency", "Sirisia Constituency", "Webuye Constituency", "Budalangi Constituency", "Butula Constituency", "Funyula Constituency", "Nambale Constituency", "Butere Constituency", "Khwisero Constituency", "Matungu Constituency", "Mumias Constituency", "Malava Constituency", "Lurambi Constituency", "Shinyalu Constituency", "Ikolomani Constituency", "Lugari Constituency", "Mt Elgon Constituency", "Amagoro Constituency", "Emuhaya Constituency", "Hamisi Constituency", "Sabatia Constituency", "Vihiga Constituency", " " }));
        constituencycombobox_election.setEnabled(false);
        constituencycombobox_election.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constituencycombobox_electionActionPerformed(evt);
            }
        });

        countycombobox_election.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        countycombobox_election.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"N/A","mombasa county", "kwale county", "kilifi county", "tanariver county", "lamu county", "taitataveta county", "garissa county", "wajir county", "mandera county", "marsabit county", "isiolo county", "meru county", "tharakanithi county", "embu county", "kitui county", "machakos county", "makueni county", "nyandarua county", "nyeri county", "kirinyaga county", "muranga county", "kiambu county", "turkana county", "westpokot county", "samburu county", "transnzoia county", "uasingishu county", "elgeyomarakwet county", "nandi county", "baringo county", "laikipia county", "nakuru county", "narok county", "kajiado county", "kericho county", "bomet county", "kakamega county", "vihiga county", "bungoma county", "busia county", "siaya county", "kisumu county", "homabay county", "migori county", "kisii county", "nyamira county", "nairobicity county" }));
        countycombobox_election.setSelectedIndex(0);
        countycombobox_election.setEnabled(false);

        county_election1.setText("County");

        cons_election1.setText("Constituency");

        ward_election1.setText("Ward");

        election_data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        election_data_table.setEnabled(false);
        jScrollPane3.setViewportView(election_data_table);

        jButton10.setText("view election data");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        ward_combo_election.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Ward" }));
        ward_combo_election.setEnabled(false);
        ward_combo_election.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ward_combo_electionActionPerformed(evt);
            }
        });

        jButton11.setText("Log Out");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(ward_election1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(add_new_election1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_button1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42)
                                    .addComponent(county_election1)
                                    .addComponent(cons_election1))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(constituencycombobox_election, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(countycombobox_election, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Election_date)
                                    .addComponent(election_id)
                                    .addComponent(type_of_election_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ward_combo_election, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton9))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11)
                                .addGap(8, 8, 8))))
                    .addComponent(jButton12))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(election_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(type_of_election_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Election_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countycombobox_election, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(county_election1))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(constituencycombobox_election, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cons_election1))))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ward_election1)
                    .addComponent(ward_combo_election, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_new_election1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_button1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
        );

        for(int i=0; i < 1 ; i++){
            election_id.setText("EL"+(int)(Math.random()*200));
        }

        electionpane.addTab("ELECTIONS", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(electionpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(electionpane, javax.swing.GroupLayout.PREFERRED_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//setting the date of the election from the date picker
        Election_date.setText(new DatePicker(f).setPickedDate());

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        select_frame sf=new select_frame();
        sf.show();
        this.show(false);
}//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to log out", "Logout", JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.OK_OPTION) {
            Log_in_form2 lf=new Log_in_form2();
            lf.show();
            this.show(false);
            
            
        } else {
            this.show(true);
        }
}//GEN-LAST:event_jButton11ActionPerformed

    private void ward_combo_electionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ward_combo_electionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ward_combo_electionActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        String sql = "Select * from election_details";
        try{
            
            rs = st.executeQuery(sql);
            st = conn.prepareStatement(sql);
            election_data_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception exp){
            JOptionPane.showMessageDialog(null, exp,"Error",JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton10ActionPerformed

    private void constituencycombobox_electionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constituencycombobox_electionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_constituencycombobox_electionActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //setting the date of the election from the date picker
        Election_date.setText(new DatePicker(f).setPickedDate());
}//GEN-LAST:event_jButton9ActionPerformed

    private void type_of_election_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_of_election_comboboxActionPerformed
        int t=type_of_election_combobox.getSelectedIndex();
        if (t==1) {
            countycombobox_election.setEnabled(true);
            constituencycombobox_election.setEnabled(false);
            ward_combo_election.setEnabled(false);
        } else if(t==2){
            constituencycombobox_election.setEnabled(true);
            countycombobox_election.setEnabled(false);
            ward_combo_election.setEnabled(false);
        }else if(t==3){
            ward_combo_election.setEnabled(true);
            constituencycombobox_election.setEnabled(false);
            countycombobox_election.setEnabled(false);
        }else{
            countycombobox_election.setEnabled(false);
            constituencycombobox_election.setEnabled(false);
            ward_combo_election.setEnabled(false);
        }
}//GEN-LAST:event_type_of_election_comboboxActionPerformed

    private void clear_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_button1ActionPerformed
        // TODO add your handling code here:
        election_id.setText("EL"+(int)(Math.random()*200));
        type_of_election_combobox.setSelectedIndex(0);
        Election_date.setText("");
        countycombobox_election.setSelectedIndex(0);
        constituencycombobox_election.setSelectedIndex(0);
        ward_combo_election.setSelectedIndex(0);
}//GEN-LAST:event_clear_button1ActionPerformed

    private void add_new_election1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_election1ActionPerformed
        
        try {
            String ele=election_id.getText();
            String type=type_of_election_combobox.getSelectedItem().toString();
            String ele_date=Election_date.getText();
            String cou=countycombobox_election.getSelectedItem().toString();
            String con=constituencycombobox_election.getSelectedItem().toString();
            String war=ward_combo_election.getSelectedItem().toString();
            if (cou == null || con==null|| war==null) {
                cou.equals("N/A");
                con.equals("N/A");
                war.equals("N/A");
            }
            
            
            try{
                String sql="INSERT INTO election_details VALUES("+
                        "'"+ele+"'," +
                        "'"+type+"',"+
                        "'"+ele_date+"',"+
                        "'"+cou+"',"+
                        "'"+con+"',"+
                        "'"+war+"')";
                
                st.execute(sql);
                JOptionPane.showMessageDialog(null,"The following has been saved successfully\n Election ID: "+ele+"\nElection Type: "+type+"\nElection Date: "+ele_date+"\nCounty: "+cou+"\nConstituency: "+con+"\nWard: "+war+"\n","Information",JOptionPane.INFORMATION_MESSAGE );
                
                
                
                
                
                
                
                
            }catch(Exception exp){
                String s=exp.getMessage();
                JOptionPane.showMessageDialog(null,"Please select the election date. ","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
            
            
            
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_add_new_election1ActionPerformed

    private void Election_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Election_dateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Election_dateActionPerformed

    private void election_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_election_idActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_election_idActionPerformed

    private void back_verificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_verificationActionPerformed
        // TODO add your handling code here:
        select_frame sf=new select_frame();
        sf.show();
        this.show(false);
}//GEN-LAST:event_back_verificationActionPerformed

    private void ward_combo_verificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ward_combo_verificationActionPerformed
        // TODO add your handling code here:
        String selected_ward=ward_combo_verification.getSelectedItem().toString();
        try {
                    
                    String sql="Select * from ward_database where name ='"+selected_ward+"'";
                    rs=st.executeQuery(sql);
                    st=conn.prepareStatement(sql);
                    while (rs.next()) { 
                    String constituency=rs.getString("county");
                    String county=rs.getString("constituency");
                    v_con.setText(constituency);
                    v_cou.setText(county);
                
            }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(electionpane, e);
        }
}//GEN-LAST:event_ward_combo_verificationActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_vActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_gActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_lnActionPerformed

    private void mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_mnActionPerformed

    private void snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_snActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
//        System.exit(0);
        int a=JOptionPane.showConfirmDialog(rootPane, "Logout ?", "LOGOUT", JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.OK_OPTION) {
            Log_in_form2 lf=new Log_in_form2();
            lf.show();
            this.show(false);
            
            
        } else {
//            this.show(true);
        }
        
    }//GEN-LAST:event_close_buttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
                          String sql_update="Update registration set place_issue = '"+place_of_issue_combo_verify.getSelectedItem().toString()+"', ward = '"+ward_combo_election.getSelectedItem().toString()+"', constituency='"+v_con.getText()+"', county = '"+v_cou.getText()+"', poll_center ='"+polling_stations_combo_ver.getSelectedItem().toString()+"' where 	id_no = '"+id.getText()+"'";
                           st =   (Statement) conn.prepareStatement(sql_update);
                            st.executeUpdate(sql_update);
                            JOptionPane.showMessageDialog(null, "Update successfull");
//


                      } catch (Exception e) {
                          JOptionPane.showMessageDialog(null, e.getMessage());
                          
                      }
}//GEN-LAST:event_jButton4ActionPerformed

    private void verification_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verification_tableMouseClicked
        // TODO add your handling code here:
        int row = verification_table.getSelectedRow();
        try {
            id.setText(verification_table.getModel().getValueAt(row, 0).toString());
            sn.setText(verification_table.getModel().getValueAt(row, 1).toString());
            mn.setText(verification_table.getModel().getValueAt(row, 2).toString());
            ln.setText(verification_table.getModel().getValueAt(row, 3).toString());
            g.setText(verification_table.getModel().getValueAt(row, 4).toString());
            //        d.setText(verification_table.getModel().getValueAt(row, 5).toString());
            v.setText(verification_table.getModel().getValueAt(row, 6).toString());
            d.setText(verification_table.getModel().getValueAt(row, 5).toString());
            v_con.setText(verification_table.getModel().getValueAt(row, 10).toString());
            v_cou.setText(verification_table.getModel().getValueAt(row, 9).toString());
            ward_combo_verification.setSelectedItem(verification_table.getModel().getValueAt(row, 8).toString());
            polling_stations_combo_ver.setSelectedItem(verification_table.getModel().getValueAt(row, 11).toString());
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_verification_tableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        verification_id_number.setText("");
        verification_voter_id.setText("");
}//GEN-LAST:event_jButton3ActionPerformed

    private void verification_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verification_buttonActionPerformed
        String temp = verification_id_number.getText() ;
        String ver=verification_voter_id.getText();
        String sql = "Select * from registration where id_no ='"+temp+"' and voter_id ='"+ver+"'";
        
        try{
            int c=0;
            rs = st.executeQuery(sql);
            st = conn.prepareStatement(sql);
            
            while(rs.next()){
                c++;
            }
            if (c==1) {
                
                
                rs = st.executeQuery(sql);
                st = conn.prepareStatement(sql);
                verification_table.setModel(DbUtils.resultSetToTableModel(rs));
            } else {
                JOptionPane.showMessageDialog(null, "ID Number: "+temp+"\nVoter ID : "+ver+"\n is not registered" );
            }
            
            
            
            
        } catch(Exception exp){
            JOptionPane.showMessageDialog(null, exp,"Error",JOptionPane.ERROR_MESSAGE);
            
            
        }
}//GEN-LAST:event_verification_buttonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        select_frame sf=new select_frame();
        sf.show();
        this.show(false);
}//GEN-LAST:event_jButton7ActionPerformed

    private void ward_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ward_comboActionPerformed
        
        String selected_ward=ward_combo.getSelectedItem().toString();
        try {
            
            String sql="Select * from ward_database where name ='"+selected_ward+"'";
            rs=st.executeQuery(sql);
            st=conn.prepareStatement(sql);
            while (rs.next()) {
                String constituency=rs.getString("county");
                String county=rs.getString("constituency");
                constituency_textfield.setText(constituency);
                county_textfield.setText(county);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(electionpane, e);
        }
}//GEN-LAST:event_ward_comboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to log out", "Logout", JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.OK_OPTION) {
            Log_in_form2 lf=new Log_in_form2();
            lf.show();
            this.show(false);
            
        } else {
            this.show(true);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        id_card_no.setText("");
        sur_name.setText("");
        Middle_name.setText("");
        last_name.setText("");
        date.setSelectedIndex(0);
        month.setSelectedIndex(0);
        year.setSelectedIndex(0);
        constituency_textfield.setText("");
        county_textfield.setText("");
        polling_stations_combo.setSelectedIndex(0);
        place_of_issue_combo.setSelectedIndex(0);
        ward_combo.setSelectedIndex(0);
        malebutton.setSelected(true);
        for(int i=0; i < 1 ; i++){
            voterid.setText(""+(int)(Math.random()*200));
        }
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_clearbuttonActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        
        String sur=sur_name.getText();
        //        String mn=
        if (sur.equals("")|| Middle_name.getText().equals("")||last_name.getText().equals("")|| ward_combo.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null, "Please fill in all your details!","INFO",JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            
            String idno=id_card_no.getText();
            int l=idno.length();
            
            int m=month.getSelectedIndex()+1;
            int y=Integer.parseInt(year.getSelectedItem().toString()) ;
            int da=Integer.parseInt(date.getSelectedItem().toString()) ;
            
            //        get the current date
            DateFormat dateFormat = new SimpleDateFormat("yyyy");
            java.util.Date leo = new java.util.Date();
            int thisYear = Integer.parseInt(dateFormat.format(leo));
            
            dateFormat = new SimpleDateFormat("MM");
            leo = new java.util.Date();
            int thisMonth = Integer.parseInt(dateFormat.format(leo));
            
            dateFormat = new SimpleDateFormat("dd");
            leo = new java.util.Date();
            int thisDay = Integer.parseInt(dateFormat.format(leo));
            
            //CREATE AN AGE VARIABLE TO HOLD THE CALCULATED AGE
            //TO START WILL – SET THE AGE EQUEL TO THE CURRENT YEAR MINUS THE YEAR
            //OF THE DOB
            int age = thisYear - y;
            
            //IF THE CURRENT MONTH IS LESS THAN THE DOB MONTH
            //THEN REDUCE THE DOB BY 1 AS THEY HAVE NOT HAD THEIR
            //BIRTHDAY YET THIS YEAR
            if(thisMonth < m){
                age = age - 1;
            }
            
            //IF THE MONTH IN THE DOB IS EQUEL TO THE CURRENT MONTH
            //THEN CHECK THE DAY TO FIND OUT IF THEY HAVE HAD THEIR
            //BIRTHDAY YET. IF THE CURRENT DAY IS LESS THAN THE DAY OF THE DOB
            //THEN REDUCE THE DOB BY 1 AS THEY HAVE NOT HAD THEIR
            //BIRTHDAY YET THIS YEAR
            if(thisMonth == m && thisDay < m){
                age = age - 1;
            }
            
            //THE AGE VARIBALE WILL NOW CONTAIN THE CORRECT AGE
            //DERIVED FROMTHE GIVEN DOB
            //        System.out.println(age);
            
            //        String n=sur_name.getText();
            //        if(n.equals("")){
            //            sur_name.setBackground(Color.lightGray);
            //        }
            if(l<8 || l>9){
                id_card_no.setBackground(Color.lightGray);
            }else if (age>17 ) {
                try {
                    String num=id_card_no.getText();
                    String surname=sur_name.getText();
                    String middle=Middle_name.getText();
                    String last=last_name.getText();
                    String gen=buttonGroup1.getSelection().getActionCommand();
                    String DOB=y+"-"+da+"-"+m;
                    String voteid=voterid.getText();
                    String p=place_of_issue_combo.getSelectedItem().toString();
                    String w=ward_combo.getSelectedItem().toString();
                    String cons=constituency_textfield.getText();
                    String cou=county_textfield.getText();
                    String pl=polling_stations_combo.getSelectedItem().toString();
                    String date_of_birth=datefield.getText();
                    
                    
                    try{
                        String sql="INSERT INTO registration VALUES("+
                                "'"+num+"'," +
                                "'"+surname+"',"+
                                "'"+middle+"',"+
                                "'"+last+"',"+
                                "'"+gen+"',"+
                                "'"+DOB+"',"+
                                "'"+voteid+"',"+
                                "'"+p+"',"+
                                "'"+w+"',"+
                                "'"+cons+"',"+
                                "'"+cou+"',"+
                                "'"+pl+"',"+
                                "'"+date_of_birth+"')";
                        
                        st.execute(sql);
                        JOptionPane.showMessageDialog(null,"The following has been saved\n ID number: "+num+"\nSir Name: "+surname+"\nMiddle Name: "+middle+"\nLast Name: "+last+"\nGender: "+gen+"\nAge: "+DOB+"\nVoter ID: "+voteid+"\nPlace of Issue: "+p+"\nWard: "+w+"\nConstituency: "+cons+"\nCounty: "+cou+"\nPolling Station: "+pl+"\nDate of Issue: "+date_of_birth+"\n","Information",JOptionPane.INFORMATION_MESSAGE );                                                                                             
                        id_card_no.setText("");
                        sur_name.setText("");
                        Middle_name.setText("");
                        last_name.setText("");
                        //                  age.setText("");
                        place_of_issue_combo.setSelectedIndex(0);
                        ward_combo.setSelectedIndex(0);
                        polling_stations_combo.setSelectedIndex(0);
                        constituency_textfield.setText("");
                        county_textfield.setText("");
                        malebutton.setSelected(true);
                        voterid.setText(""+(int)(Math.random()*200));
                        year.setSelectedIndex(0);
                        month.setSelectedIndex(0);
                        date.setSelectedIndex(0);
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                    }catch(SQLException exp){
                        
                        JOptionPane.showMessageDialog(null, exp.getMessage());
                    }
                    
                } catch (Exception e) {
                    
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                
            } else {
                
                JOptionPane.showMessageDialog(null,"Sorry your age is below the expected minimum of 18 years.","ERROR",JOptionPane.ERROR_MESSAGE);
                
            }
        }
        
        
        
        
        
        
    }//GEN-LAST:event_savebuttonActionPerformed

    private void place_of_issue_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place_of_issue_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_place_of_issue_comboActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
                      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    } catch (Exception e) {
                      System.err.println("Look and feel not set.");
                    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new after_login_interface().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Election_date;
    private javax.swing.JTextField Middle_name;
    private javax.swing.JButton add_new_election1;
    private javax.swing.JButton back_verification;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton clear_button1;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel cons_election1;
    private javax.swing.JTextField constituency_textfield;
    private javax.swing.JComboBox constituencycombobox_election;
    private javax.swing.JLabel county_election1;
    private javax.swing.JTextField county_textfield;
    private javax.swing.JComboBox countycombobox_election;
    private javax.swing.JTextField d;
    private javax.swing.JComboBox date;
    private javax.swing.JFormattedTextField datefield;
    private javax.swing.JTable election_data_table;
    private javax.swing.JTextField election_id;
    private javax.swing.JTabbedPane electionpane;
    private javax.swing.JRadioButton femalebutton;
    private javax.swing.JTextField g;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id_card_no;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField ln;
    private javax.swing.JRadioButton malebutton;
    private javax.swing.JTextField mn;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox place_of_issue_combo;
    private javax.swing.JComboBox place_of_issue_combo_verify;
    private javax.swing.JComboBox polling_stations_combo;
    private javax.swing.JComboBox polling_stations_combo_ver;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField sn;
    private javax.swing.JTextField sur_name;
    private javax.swing.JComboBox type_of_election_combobox;
    private javax.swing.JTextField v;
    private javax.swing.JTextField v_con;
    private javax.swing.JTextField v_cou;
    private javax.swing.JButton verification_button;
    private javax.swing.JTextField verification_id_number;
    private javax.swing.JTable verification_table;
    private javax.swing.JTextField verification_voter_id;
    private javax.swing.JTextField voterid;
    private javax.swing.JComboBox ward_combo;
    private javax.swing.JComboBox ward_combo_election;
    private javax.swing.JComboBox ward_combo_verification;
    private javax.swing.JLabel ward_election1;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables

}
