package MVoter;



import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Log_in_form2.java
 *
 * 
 */

/**
 *
 * @author Kimaiga
 */
public class Log_in_form2 extends javax.swing.JFrame {
    Connection conn= null;
    String url = "jdbc:mysql://localhost/";
    String dbName = "db66001";
    String driver ="com.mysql.jdbc.Driver";
    String user = "root";
    String password = "";

    /*Connection conn = null;
    String url = "jdbc:mysql://192.168.170.15/";
    String dbName = "db66001";
    String driver = "com.mysql.jdbc.Driver";
    String userName = "66001";
    String password = "66001";*/
    Statement st;
    ResultSet rs;
    JLabel ul,pl,npl,cpl;
    JTextField ut;
    JPasswordField up,np,cp;
    PasswordService ps;
    static final int MY_MINIMUM = 0;
    static final int MY_MAXIMUM = 100;

    /** Creates new form Log_in_form2 */
    public Log_in_form2() {
        
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        ps=new PasswordService();
        
                try{
	       Class.forName(driver);

             conn = DriverManager.getConnection(url+dbName,user,password);

              st = conn.createStatement();

             this.setTitle("Login");

	            }


	            catch(Exception exp)
                    {
                      JOptionPane.showMessageDialog(null, "Cannot connect to the database,check network settings.","ERROR",JOptionPane.ERROR_MESSAGE);
                      
	            }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        userpass = new javax.swing.JPasswordField();
        new_pass_label = new javax.swing.JLabel();
        con_pass_label = new javax.swing.JLabel();
        new_pass_txt = new javax.swing.JTextField();
        con_pass_txt = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVoter/IEBC.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setMaximumSize(new java.awt.Dimension(105, 112));
        jLabel1.setMinimumSize(new java.awt.Dimension(105, 112));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("       CONTROL PANEL");

        ID_label.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID_label.setText("Net ID");

        pass_label.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pass_label.setText("Password");

        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });

        login_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVoter/key.png"))); // NOI18N
        login_button.setText("Log In");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        cancel_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVoter/clear_left.png"))); // NOI18N
        cancel_button.setText("Clear");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        new_pass_label.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        new_pass_label.setText("New Password");

        con_pass_label.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        con_pass_label.setText("Confirm New Password");
        con_pass_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        con_pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_pass_txtActionPerformed(evt);
            }
        });

        save.setText("EXIT");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel6.setText("Reset Password");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel4.setText("<html><a href='http://www.google.co.ke/firefox'>help</a></html>");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("@SYSLOG CORPORATION-2015");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("<html><a href='http://www.google.co.ke/firefox'>help</a></html>");
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVoter/groupon_logo.png"))); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVoter/groupon_logo.png"))); // NOI18N
        //jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(new_pass_label)
                                                .addGap(71, 71, 71))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(con_pass_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(89, 89, 89)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userpass, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(new_pass_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(con_pass_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(user_id, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(save))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cancel_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(login_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ID_label)
                    .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_label)
                    .addComponent(userpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_pass_label)
                    .addComponent(new_pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(con_pass_label)
                    .addComponent(con_pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(save)
                            .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        new_pass_label.setVisible(false);
        con_pass_label.setVisible(false);
        new_pass_txt.setVisible(false);
        con_pass_txt.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed

//        PasswordService ps=new PasswordService();
        String user=user_id.getText();
        String pass=userpass.getText();
        if("".equals(user) ||"".equals(pass))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter your username and password.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
        try {
            
            String passenc=ps.encrypt(pass);
              try {
                 String sql="SELECT * FROM projectlogin WHERE username='"+user+"'and userpassword ='"+passenc+"'";
                 st.execute(sql);
                  rs=st.executeQuery(sql);
                  int c=0;
                  while(rs.next())
                  {
                    c++;
                    String level=rs.getString("level");
                  if (c==1 && "Administrator".equals(level)) 
                  {
                      select_frame sf=new select_frame();
                      sf.setVisible(true);
                      this.setVisible(false);

                     
                  }
                  else if(c==1 && "Station Officer".equals(level)){
                    JOptionPane.showMessageDialog(rootPane, "You are logging in as Returning Officer....");
                    new StationOfficer().show();
                    this.dispose();
                }
               
               
                  
                  
                }
                  
                  
            } catch (Exception f) {
                JOptionPane.showMessageDialog(rootPane, f.getMessage());
            }
        } catch (Exception ex) {
            Logger.getLogger(Log_in_form2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
                
        // TODO add your handling code here:
    }//GEN-LAST:event_login_buttonActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        new_pass_label.setVisible(false);
        new_pass_txt.setVisible(false);
        con_pass_label.setVisible(false);
        con_pass_txt.setVisible(false);
        login_button.setEnabled(true);
        userpass.setText("");
        user_id.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
  
        // TODO add your handling code here:
        /*
         * ps=new PasswordService();
        try {
            String passenc=ps.encrypt(pass);
              try {
            String sql="INSERT INTO projectlogin VALUES("+                              
                              "'"+user+"',"+
	                       "'"+passenc+"')";

	              st.execute(sql);
	                JOptionPane.showMessageDialog(null,"SAVED","Information",JOptionPane.INFORMATION_MESSAGE );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage()+passenc);
        }
        } catch (Exception ex) {
            Logger.getLogger(Log_in_form2.class.getName()).log(Level.SEVERE, null, ex);
        }
         */
        int a=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "EXIT", JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.OK_OPTION) {
            System.exit(0);
            
            
        } else {
//            this.show(true);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked





//        new_pass_label.setVisible(true);
//        new_pass_txt.setVisible(true);
//        con_pass_label.setVisible(true);
//        con_pass_txt.setVisible(true);
//        login_button.setEnabled(false);
        

        // TODO add your handling code here:
        
        
        
        JPanel panel=new JPanel();
        panel.setLayout(new GridLayout(4, 2));
        //the labels
        ul=new JLabel("User ID");
        pl=new JLabel("Old Password");
        npl=new JLabel("New Password");
        cpl=new JLabel("Confirm Password");

        //the textfield
        ut=new JTextField();
        ut.setSize(50, 15);

        //the passwordfields
        up=new JPasswordField();
        up.setSize(50, 15);
        np=new JPasswordField();
        np.setSize(50, 15);
        cp=new JPasswordField();
        cp.setSize(50, 15);



        panel.add(ul);
        panel.add(ut);
        panel.add(pl);
        panel.add(up);
        panel.add(npl);
        panel.add(np);
        panel.add(cpl);
        panel.add(cp);
        int a=JOptionPane.showConfirmDialog(null, panel,"RESET PASSWORD",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        if(a==JOptionPane.OK_OPTION) {
            String username=ut.getText();
            String userpassword=up.getText();
            String newpassword=np.getText();
            String confirmpassword=cp.getText();
            int newpasswordlength=newpassword.length();
            
            if (username.equals("")||userpassword.equals("")||newpassword.equals("")||confirmpassword.equals("")) {
                JOptionPane.showMessageDialog(panel, "Fill all the entries");
            } else if(!newpassword.equals(confirmpassword)) {
                JOptionPane.showMessageDialog(null, "<html><font color=red>Passwords are not the same</font></html>");
            }else if(newpasswordlength >10 ||newpasswordlength ==10){
                
                ////what happens if password is not null and new and confirm pass are equal
             try {
                //            String passenc=ps.encrypt(userpassword);
                            String userpassencrypted=ps.encrypt(userpassword);
                            
                            try {
                 String sql="SELECT * FROM projectlogin WHERE username='"+username+"'and userpassword ='"+userpassencrypted+"'";
                 st.execute(sql);
                  rs=st.executeQuery(sql);
                  int c=0;
                  while(rs.next()){
                    c++;
                    }
                  if (c==1) {
                      String encryptednewpassword=ps.encrypt(newpassword);
//                      String sql = "Update projectlogin set  sname ='"+sname.getText()+"',mname ='"+mname.getText()+"', lname ='"+lname.getText()+"', level ='"+admin_combobox.getSelectedItem().toString()+"' where username='"+del_id+"'";
////                String sqla = "update projectlogin set First_Name = '"+fnm.getText().toString()+"',Last_Name= '"+lnm.getText().toString()+""+"',Gender='" + sex.getSelectedItem().toString() +"',DOB= '" + format.format(age.getDate()) +"',Mobile_No='"+mob.getText().toString()+"',Address= '"+add.getText().toString()+ "',Role='"+pos.getText().toString()+"',Salary= '"+salo.getText()+"',Health_Status= '"+hlt.getText()+"' where Staff_No= '"+staff.getText()+"'";
//
//                        try{
//
//                           st =     (Statement) conn.prepareStatement(sql);
//                            st.executeUpdate(sql);
//
//
//                        } catch(Exception exp){
//                            JOptionPane.showMessageDialog(null, exp,"Error",JOptionPane.ERROR_MESSAGE);
//
//                        }
                      try {
                          String sql_update="Update projectlogin set userpassword = '"+encryptednewpassword+"' where username = '"+username+"'";
                           st =   (Statement) conn.prepareStatement(sql_update);
                            st.executeUpdate(sql_update);
                            JOptionPane.showMessageDialog(null, "Password Changed");
//


                      } catch (Exception e) {
                          JOptionPane.showMessageDialog(null, e.getMessage());
                          
                      }
                      

                     
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Cannot reset Password/nInvalid username, password combination");
//                    System.err.println("Error");
                   
                  }
            } catch (Exception f) {
                JOptionPane.showMessageDialog(rootPane, f.getMessage());
                
            }
                            
            } catch (Exception ex) {
                Logger.getLogger(Log_in_form2.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Password Length should be 8 or more.");
                
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        if (evt.getClickCount() > 0) {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    URI uri = new URI("http://support.google.com/mail/bin/answer.py?hl=en&answer=6567");
                    desktop.browse(uri);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(Log_in_form2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    // do nothing
                }
            } else {
                //do nothing
            }

        }
}//GEN-LAST:event_jLabel4MouseClicked

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_idActionPerformed

    private void con_pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_pass_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_pass_txtActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new SplashScreen(1000);
        
        //</editor-fold>

        /*
         * Create and display the form
         */
        try {          
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            } catch (Exception x) 
        {
            
        }
        
        final ProgressBar mysplash = new ProgressBar();
        for (int i = MY_MINIMUM; i <= MY_MAXIMUM; i++) {
            final int percent = i;
            try {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        mysplash.setVisible(true);
                        mysplash.updateBar(percent);
                        new ProgressBar();
                    }
                    
                });
                java.lang.Thread.sleep(105);
            } catch (InterruptedException e) {
                
            }
            
        }


        
        try {
                      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    } catch (Exception e) {
                      System.err.println("Look and feel not set.");
                    }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Log_in_form2().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_label;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel con_pass_label;
    private javax.swing.JTextField con_pass_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel new_pass_label;
    private javax.swing.JTextField new_pass_txt;
    private javax.swing.JLabel pass_label;
    private javax.swing.JButton save;
    private javax.swing.JTextField user_id;
    private javax.swing.JPasswordField userpass;
    // End of variables declaration//GEN-END:variables

}
