package MVoter;


import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * select_frame.java
 *
 * 
 */
/**
 *
 * @author Kimaiga
 */
public class select_frame extends javax.swing.JFrame {

    /** Creates new form select_frame */
    public select_frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shoe_afterlogin_form_ = new javax.swing.JButton("<html>VOTER REGISTRATION AND<br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; VERIFICATION </html>");
        show_cand_registration_form_ = new javax.swing.JButton();
        show_electoral_boundary_form_ = new javax.swing.JButton();
        show_voting_form_ = new javax.swing.JButton();
        result_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        view_tablessssss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Options");

        shoe_afterlogin_form_.setFont(new java.awt.Font("Times New Roman", 1, 11));
        shoe_afterlogin_form_.setForeground(java.awt.Color.darkGray);
        shoe_afterlogin_form_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoe_afterlogin_form_ActionPerformed(evt);
            }
        });

        show_cand_registration_form_.setFont(new java.awt.Font("Times New Roman", 1, 11));
        show_cand_registration_form_.setText("CANDIDATE REGISTRATION");
        show_cand_registration_form_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_cand_registration_form_ActionPerformed(evt);
            }
        });

        show_electoral_boundary_form_.setFont(new java.awt.Font("Times New Roman", 1, 11));
        show_electoral_boundary_form_.setText("ELECTORAL BOUNDARIES");
        show_electoral_boundary_form_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_electoral_boundary_form_ActionPerformed(evt);
            }
        });

        show_voting_form_.setFont(new java.awt.Font("Times New Roman", 1, 11));
        show_voting_form_.setText("VOTING");
        show_voting_form_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_voting_form_ActionPerformed(evt);
            }
        });

        result_button.setFont(new java.awt.Font("Times New Roman", 1, 11));
        result_button.setText("VIEW RESULTS");
        result_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_buttonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jButton1.setText("USER MANAGEMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        view_tablessssss.setFont(new java.awt.Font("Times New Roman", 1, 11));
        view_tablessssss.setText("VIEW TABLES");
        view_tablessssss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_tablessssssActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(logout_button)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(result_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(show_voting_form_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(shoe_afterlogin_form_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(show_electoral_boundary_form_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(show_cand_registration_form_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(view_tablessssss, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(shoe_afterlogin_form_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show_cand_registration_form_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show_electoral_boundary_form_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show_voting_form_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(result_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_tablessssss, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(logout_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shoe_afterlogin_form_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoe_afterlogin_form_ActionPerformed

        after_login_interface al=new after_login_interface();
        al.show();
        this.show(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_shoe_afterlogin_form_ActionPerformed

    private void show_electoral_boundary_form_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_electoral_boundary_form_ActionPerformed

        electoral_boundaries eb=new electoral_boundaries();
        eb.show();
        this.show(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_show_electoral_boundary_form_ActionPerformed

    private void show_cand_registration_form_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_cand_registration_form_ActionPerformed

        candidate_form cf=new candidate_form();
        cf.show();
        this.show(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_show_cand_registration_form_ActionPerformed

    private void show_voting_form_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_voting_form_ActionPerformed

        voting_for_candidate v=new voting_for_candidate();
        v.show();
        this.show(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_show_voting_form_ActionPerformed

    private void result_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_buttonActionPerformed
        // TODO add your handling code here:
        view_results vr=new view_results();
        vr.show();
        this.show(false);
    }//GEN-LAST:event_result_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\
        add_new_user adu=new add_new_user();
        adu.show();
        this.show(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to log out", "Logout", JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.OK_OPTION) {
            Log_in_form2 lg=new Log_in_form2();
            this.show(false);
            lg.show();
            
        } else {
            this.show(true);
        }
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void view_tablessssssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_tablessssssActionPerformed
        // TODO add your handling code here:
        view_tables vt=new view_tables();
        vt.show();
        this.show(false);
    }//GEN-LAST:event_view_tablessssssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
                      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    } catch (Exception e) {
                      System.err.println("Look and feel not set.");
                    }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new select_frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton result_button;
    private javax.swing.JButton shoe_afterlogin_form_;
    private javax.swing.JButton show_cand_registration_form_;
    private javax.swing.JButton show_electoral_boundary_form_;
    private javax.swing.JButton show_voting_form_;
    private javax.swing.JButton view_tablessssss;
    // End of variables declaration//GEN-END:variables
}
