package MVoter;

import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StationOfficer.java
 *
 * 
 */
/**
 *
 * @author Kimaiga
 */

public class StationOfficer extends javax.swing.JFrame {

    /** Creates new form StationOfficer */
    public StationOfficer() 
    {
        super("Station Officer");
        try {          
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            } catch (Exception x) 
        {
            
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show_voting_form_ = new javax.swing.JButton();
        result_button = new javax.swing.JButton();
        view_tablessssss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        show_voting_form_.setFont(new java.awt.Font("Times New Roman", 1, 11));
        show_voting_form_.setText("VOTING");
        show_voting_form_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_voting_form_ActionPerformed(evt);
            }
        });

        result_button.setFont(new java.awt.Font("Times New Roman", 1, 11));
        result_button.setText("VIEW RESULTS");
        result_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_buttonActionPerformed(evt);
            }
        });

        view_tablessssss.setFont(new java.awt.Font("Times New Roman", 1, 11));
        view_tablessssss.setText("VIEW TABLES");
        view_tablessssss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_tablessssssActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(result_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(view_tablessssss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(show_voting_form_, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(show_voting_form_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_tablessssss, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(result_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_voting_form_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_voting_form_ActionPerformed
        
        voting_for_candidate v=new voting_for_candidate();
        v.show();
        this.show(false);
        // TODO add your handling code here:
}//GEN-LAST:event_show_voting_form_ActionPerformed

    private void result_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_buttonActionPerformed
        // TODO add your handling code here:
        view_results vr=new view_results();
        vr.show();
        this.show(false);
}//GEN-LAST:event_result_buttonActionPerformed

    private void view_tablessssssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_tablessssssActionPerformed
        // TODO add your handling code here:
        view_tables vt=new view_tables();
        vt.show();
        this.show(false);
}//GEN-LAST:event_view_tablessssssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StationOfficer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton result_button;
    private javax.swing.JButton show_voting_form_;
    private javax.swing.JButton view_tablessssss;
    // End of variables declaration//GEN-END:variables
}
